### PR TITLE
🐛 fix cb password reset validation issues

### LINKED ISSUE #519: 🐛 Password reset error
User tried to reset their password but got multiple errors
- [no special char] too weak with no explanation why
- [with !] token has expired
- [with ?] too weak

### PR DESCRIPTION
**Pull request by astroash**
Changes:
- add more special characters to regex
- extend token lifespan to 1 day
- clarify error messages
- add password strength critera on client

Fixes #519

### CODE REVIEW

File: server/routes/cbauthentication/cb_password_change.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ const schemas = {
     token: Joi.string().required(),
 
     password: Joi.string()
-      .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{8,})/, 'strong_pwd')
+      .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!#$%&()*+,-./:;<=>?@[\]^_{|}~?])(?=.{8,})/, 'strong_pwd')
```
Comment (eliascodes) [inline server/routes/cbauthentication/cb_password_change.js]: Do `$`, `^`, `?`, `.`, `*`, need to be escaped? Also you've `?` twice.

Comment (astroash) [reply server/routes/cbauthentication/cb_password_change.js]: @eliascodes quantifiers don't work in character sets, but I have missed a few escapes.
